steps:
  - name: 'bash'
    args: ['sleep', '1']
  - name: 'bash'
    args: ['sleep', '2']
  - name: 'bash'
    args: ['sleep', '4']
  - name: 'bash'
    args: ['sleep', '8']
  - name: 'bash'
    args: ['sleep', '16']
  - name: 'bash'
    args: ['sleep', '32']
  - name: 'bash'
    args: ['sleep', '64']
  - name: 'bash'
    args: ['sleep', '128']
  - name: 'bash'
    args: ['sleep', '256']
